# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(643, 383)
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_header.setGeometry(QtCore.QRect(180, 30, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.button_vote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_vote.setGeometry(QtCore.QRect(90, 110, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        self.button_vote.setFont(font)
        self.button_vote.setObjectName("button_vote")
        self.button_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_exit.setEnabled(True)
        self.button_exit.setGeometry(QtCore.QRect(340, 110, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        self.button_exit.setFont(font)
        self.button_exit.setObjectName("button_exit")
        self.label_output = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(140, 230, 341, 111))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_output.setFont(font)
        self.label_output.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_output.setObjectName("label_output")
        self.button_vote_jake = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_vote_jake.setEnabled(True)
        self.button_vote_jake.setGeometry(QtCore.QRect(90, 110, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        self.button_vote_jake.setFont(font)
        self.button_vote_jake.setCheckable(False)
        self.button_vote_jake.setAutoDefault(False)
        self.button_vote_jake.setDefault(False)
        self.button_vote_jake.setFlat(False)
        self.button_vote_jake.setObjectName("button_vote_jake")
        self.button_vote_jane = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_vote_jane.setEnabled(True)
        self.button_vote_jane.setGeometry(QtCore.QRect(340, 110, 181, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        self.button_vote_jane.setFont(font)
        self.button_vote_jane.setObjectName("button_vote_jane")
        self.button_vote_jake.raise_()
        self.button_vote.raise_()
        self.label_header.raise_()
        self.label_output.raise_()
        self.button_vote_jane.raise_()
        self.button_exit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_header.setText(_translate("MainWindow", "VOTE MENU"))
        self.button_vote.setText(_translate("MainWindow", "VOTE"))
        self.button_exit.setText(_translate("MainWindow", "EXIT"))
        self.label_output.setText(_translate("MainWindow", "Please select an option"))
        self.button_vote_jake.setText(_translate("MainWindow", "JAKE"))
        self.button_vote_jane.setText(_translate("MainWindow", "JANE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
